os:
  - linux
  - osx

language: cpp

compiler:
    - gcc
    - clang

before_install:
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - if [ "$CXX" == "clang++" -a "$CPP14" == "0" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
    - sudo apt-get update -qq

install:
    # g++ 4.9
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

    # clang 3.5
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install clang-3.5; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.5"; fi

before_script:
    - cmake .

script:
    - make

notifications:
    email:
    - neveralso@qq.com

#matrix:
#    allow_failures:
#    - os: linux
