os:
  - linux
  - osx

language: cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update

install:
    # g++ 4.9
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

    # clang 3.5
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq clang-3.5; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.5"; fi

before_script:
    - cmake .

script:
    - make

notifications:
    email:
    - neveralso@qq.com

#matrix:
#    allow_failures:
#    - os: linux
