os:
  - linux
  - osx

language: cpp

compiler:
    - gcc
    - clang

before_script:
    - cmake .

script: make

notifications:
    email:
    - neveralso@qq.com
    - neveralso@gmail.com

matrix:
    allow_failures:
    - os: linux
